### ISSUE TITLE
As a server admin, I want to host multiple authors on my server

### ISSUE THREAD

**Issue by kdhaywar** [kdhaywar/CMPUT404-project-socialdistribution#13]
<a href="https://github.com/kdhaywar"><img src="https://avatars.githubusercontent.com/u/8973253?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kdhaywar](https://github.com/kdhaywar)**
_Tuesday Jan 19, 2016 at 17:16 GMT_
_Originally opened as https://github.com/shawnwanderson/cmput404-project/issues/13_

---

**Comment by YufeiZhang** [comment]
This one is done
