### ISSUE TITLE
As a server admin, I want to be able allow users to sign up but require my OK to finally be on my server

### ISSUE THREAD

**Issue by kdhaywar** [kdhaywar/CMPUT404-project-socialdistribution#26]
<a href="https://github.com/kdhaywar"><img src="https://avatars.githubusercontent.com/u/8973253?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kdhaywar](https://github.com/kdhaywar)**
_Tuesday Jan 19, 2016 at 17:19 GMT_
_Originally opened as https://github.com/shawnwanderson/cmput404-project/issues/26_

---

**Comment by timoteialbu** [comment]
Done, though I think we might wanna make the admin's ability to activate multiple users easier.
