### ISSUE TITLE
Login is broken 

### ISSUE THREAD

**Issue by kdhaywar** [kdhaywar/CMPUT404-project-socialdistribution#43]
it does add the accounts as seen in admin
# **http://127.0.0.1:8000/accounts/login/**
## returns

ImproperlyConfigured at /accounts/login/

No Facebook app configured: please add a SocialApp using the Django admin

Request Method:     GET
Request URL:    http://127.0.0.1:8000/accounts/login/
Django Version:     1.8.9
Exception Type:     ImproperlyConfigured
Exception Value:    

No Facebook app configured: please add a SocialApp using the Django admin

Exception Location:     /home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/local/lib/python2.7/site-packages/allauth/socialaccount/providers/facebook/provider.py in media_js, line 133
Python Executable:  /home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/bin/python
Python Version:     2.7.10
Python Path:    

['/home/kyle/Desktop/CMPUT404-project-socialdistribution',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-tk',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-old',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/local/lib/python2.7/site-packages',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/site-packages']

Server time:    Wed, 17 Feb 2016 14:26:45 -0700
# **http://127.0.0.1:8000/accounts/signup/**
## Works but when I submit it returns

error at /accounts/signup/

[Errno 111] Connection refused

Request Method:     POST
Request URL:    http://127.0.0.1:8000/accounts/signup/
Django Version:     1.8.9
Exception Type:     error
Exception Value:    

[Errno 111] Connection refused

Exception Location:     /usr/lib/python2.7/socket.py in create_connection, line 575
Python Executable:  /home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/bin/python
Python Version:     2.7.10
Python Path:    

['/home/kyle/Desktop/CMPUT404-project-socialdistribution',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-tk',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-old',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/local/lib/python2.7/site-packages',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/site-packages']

Server time:    Wed, 17 Feb 2016 14:28:24 -0700
# after signing up I am unable to to post

ValueError at /posts/create_img/

Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f81ae5a0bd0>>": "Image.author" must be a "User" instance.

Request Method:     POST
Request URL:    http://127.0.0.1:8000/posts/create_img/
Django Version:     1.8.9
Exception Type:     ValueError
Exception Value:    

Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f81ae5a0bd0>>": "Image.author" must be a "User" instance.

Exception Location:     /home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/local/lib/python2.7/site-packages/django/db/models/fields/related.py in **set**, line 642
Python Executable:  /home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/bin/python
Python Version:     2.7.10
Python Path:    

['/home/kyle/Desktop/CMPUT404-project-socialdistribution',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-tk',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-old',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/local/lib/python2.7/site-packages',
 '/home/kyle/Desktop/CMPUT404-project-socialdistribution/venv/lib/python2.7/site-packages']

Server time:    Wed, 17 Feb 2016 14:39:33 -0700

**Comment by timoteialbu** [comment]
Its all fixed bruh
