### ISSUE TITLE
/posts doesnt load if no posts exist 

### ISSUE THREAD

**Issue by kdhaywar** [kdhaywar/CMPUT404-project-socialdistribution#45]
If no posts exist /posts/ returns 404 (I think).  Should add a constraint to check for empty conditions

**Comment by aaclark** [comment]
--project/CMPUT404-project-socialdistribution/posts/views.py in index
                latest_post_list = get_posts(request) ...
▶ Local vars
--project/CMPUT404-project-socialdistribution/posts/views.py in get_posts
                    Q(author=request.user)) ...
▶ Local vars
